spring:
  datasource:
    url: jdbc:h2:mem:test_h2
    driverClassName: org.h2.Driver
    username: sa
    password:
    schema: classpath*:db/schema.sql
    data: classpath*:db/data.sql

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate: ddl-auto=validate
    hibernate.ddl-auto: validate
    show-sql: true

  h2.console:
    enabled: true
    path: /h2
    setting:
      trace: false
      web-allow-others: false
